name: E2E Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'packages/viewer/**'
      - '.github/workflows/e2e-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/viewer/**'
      - '.github/workflows/e2e-tests.yml'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
    
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Build viewer
      run: pnpm -F @passport/viewer build
      
    - name: Install Playwright Browsers
      run: pnpm -F @passport/viewer test:e2e:install
      
    - name: Run Playwright tests
      run: pnpm -F @passport/viewer test:e2e
      
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: packages/viewer/playwright-report/
        retention-days: 30
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: packages/viewer/test-results/
        retention-days: 7